### ISSUE TITLE
라이센스 정책

### ISSUE THREAD

**Issue by hyunjik-song** [ksjae/KoGPT#5]
안녕하세요. https://static.ksjit.com/datasets/tinyDedup.txt 데이터의 라이센스 정책이 궁금합니다. 감사합니다.

**Comment by ksjae** [comment]
README에 쓰인 소스 Citation 필수 (최대 CC-BY, 일부 CC0, 일부 라이센스 조항 없음) 조건으로 이용하면 됩니다.

*저는 변호사가 아닙니다. 법적인 내용에 관해서는 잘 모릅니다.*

**Comment by ksjae** [comment]
더 이상의 활동이 없기 때문에 이슈를 닫습니다.
